# Generated by Django 2.2.3 on 2019-08-06 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name="dancer's first name")),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name of formation')),
                ('in_use', models.BooleanField(default=False, verbose_name='Currently in use')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(verbose_name='x-coordinate')),
                ('y', models.IntegerField(verbose_name='y-coordinate')),
                ('dancer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position', to='draw.Dancer')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='draw.Formation')),
            ],
        ),
    ]
