# Generated by Django 2.2.3 on 2019-08-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0003_auto_20190810_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Formation notes'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='Formation image base64 data'),
        ),
    ]
