# Generated by Django 2.2.4 on 2019-08-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0004_auto_20190810_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dancer',
            name='color',
        ),
        migrations.AddField(
            model_name='position',
            name='color',
            field=models.CharField(default='White', max_length=30),
        ),
    ]
